add retry for curl

diff --git a/.github/workflows/utils.yaml b/.github/workflows/utils.yaml
--- a/.github/workflows/utils.yaml
+++ b/.github/workflows/utils.yaml
@@ -90,7 +90,29 @@ jobs:
       - name: Generate diff.patch
         run: |
           cd $GITHUB_WORKSPACE/matrixone
-          curl -L "https://github.com/matrixorigin/matrixone/pull/${{ github.event.pull_request.number }}.diff" > diff.patch
+          retry_times=5
+          delay=5
+          url="https://github.com/matrixorigin/matrixone/pull/${{ github.event.pull_request.number }}.diff"
+          
+          for ((i=1; i<=$retry_times; i++)); do
+            response=$(curl --max-time 10 -o /dev/null -w "%{http_code}" $url)
+            echo "respCode: $response"
+            if [ "$response" == "200" ];then
+                curl -L -s $url > diff.patch
+                if [ -f "$GITHUB_WORKSPACE/matrixone/diff.patch" ];then
+                echo "Get diff.patch success..."
+                break
+              fi
+            fi
+            echo "Get diff.patch failed...Retrying in 3 seconds..."
+            sleep $delay
+          done
+
+          if [ "$i" -gt $retry_times ]; then
+              echo "Max retries reached. Failed."
+              exit 1
+          fi
+
       - name: Set up Go and JAVA
         uses: matrixorigin/CI/actions/setup-env@main
         with:
