New failed-ut-case action (#197)
* ut test insert failed to moc for main

* ut test insert failed to moc for main

diff --git a/.github/workflows/utils.yaml b/.github/workflows/utils.yaml
--- a/.github/workflows/utils.yaml
+++ b/.github/workflows/utils.yaml
@@ -210,8 +210,81 @@ jobs:
           test_scope=$(go list ./... | grep -v 'driver\|engine/aoe\|engine/memEngine\|pkg/catalog')
           make clean && make config && make cgo
           echo "ut start"
-          CGO_CFLAGS="-I${GITHUB_WORKSPACE}/matrixone/cgo" CGO_LDFLAGS="-L${GITHUB_WORKSPACE}/matrixone/cgo -lmo" go test -short -v -tags matrixone_test -p 6 -covermode=set -coverprofile=${{ env.raw_ut_coverage }} -coverpkg=./... ${test_scope} | tee ${{ env.ut_report }}
+          CGO_CFLAGS="-I${GITHUB_WORKSPACE}/matrixone/cgo" CGO_LDFLAGS="-L${GITHUB_WORKSPACE}/matrixone/cgo -lmo" go test -json -short -v -tags matrixone_test -p 6 -covermode=set -coverprofile=${{ env.raw_ut_coverage }} -coverpkg=./... ${test_scope} | tee ${{ env.ut_report }}
           echo "ut finished"
+      - name: Analysis Fail UT Cases
+        if: ${{ failure() }}
+        run: |
+          go install github.com/matrixorigin/go-ut-analysis@latest
+          go-ut-analysis test -f "$GITHUB_WORKSPACE/matrixone/${{ env.ut_report }}" --first 10 --report-path  "$GITHUB_WORKSPACE/ut-report" --stdout=false;
+          if find ut-report > /dev/null 2>&1 && ! find ut-report/failed/outputs > /dev/null 2>&1; then
+            logger "INF" "UNIT TESTING SUCCEEDED !!!"
+          else
+            logger "INF" "UNIT TESTING FAILED !!!"
+            exit 1;
+          fi
+      - name: Parse Time for moc
+        if: ${{ failure() }}
+        id: time
+        run: |
+          export TZ='Asia/Shanghai'
+
+          #utcTime="2024-11-15T08:33:52Z"
+          action_time=${{ github.event.pull_request.head.repo.pushed_at }}
+          ACTION_TIME=$(date -d "${action_time}" '+%Y-%m-%d %H:%M:%S')
+
+          # 获取格式化的日期时间字符串
+          time=$(date '+%Y-%m-%d %H:%M:%S')
+
+          # action link
+          action_link="https://github.com/${{ github.event.pull_request.base.repo.full_name }}/actions/runs/${{ github.run_id }}"
+
+          echo "ACTION_TIME=${ACTION_TIME}"
+          echo "START_TIME=${time}"
+          echo "ACTION_LINK=${action_link}"
+
+          echo "ACTION_TIME=${ACTION_TIME}" >> $GITHUB_OUTPUT
+          echo "START_TIME=${time}" >> $GITHUB_OUTPUT
+          echo "ACTION_LINK=${action_link}" >> $GITHUB_OUTPUT
+
+      - name: Get failed ut cases
+        if: ${{ failure() }}
+        id: failed
+        run: |
+          cd $GITHUB_WORKSPACE;
+          if [ "$(find ./ut-report/failed | wc -l)" -le "2" ]; then
+            exit 0;
+          fi
+          find ./ut-report/failed -name result.txt -exec cat {} \;
+          fail_ut_cases=''
+          files=($(find ./ut-report/failed | grep -v result.txt))
+          for file in "${files[@]}"; do
+            if [ -d "$file" ]; then
+              continue
+            fi
+            echo "============================================"
+            cat "${file}";
+            fail_ut_cases=${fail_ut_cases}$(basename "${file}")','
+          done
+
+          echo "steps.ut.conclusion: ${{ steps.ut.conclusion }}"
+          echo "FAIL_UT_CASES=${fail_ut_cases}"
+          echo "FAIL_UT_CASES=${fail_ut_cases}" >> $GITHUB_OUTPUT
+      - name: Insert Failed UT Cases to MOC
+        if: ${{ failure() }}
+        uses: matrixorigin/CI/actions/fail-ut-case@main
+        with:
+          action_time: ${{ steps.time.outputs.ACTION_TIME }}
+          ut_cases: ${{ steps.failed.outputs.FAIL_UT_CASES }}
+          pr_link: ${{ github.event.pull_request.html_url }}
+          action_link: ${{ steps.time.outputs.ACTION_LINK }}
+          job_time: ${{ steps.time.outputs.START_TIME }}
+          mo_host: ${{ secrets.EE_DB_ADDR }}
+          mo_port: ${{ secrets.EE_DB_PORT }}
+          mo_user: ${{ secrets.EE_DB_USER }}
+          mo_password: ${{ secrets.EE_DB_PASSWORD }}
+          mo_database: ${{ secrets.EE_DB_DB }}
+
       - name: Start BVT Test Service
         timeout-minutes: 10
         run: |
